apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: boardgame-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /  # Ensures proper routing for the backend
spec:
  rules:
  - host: nizam.work.gd  # Replace with your custom domain or external IP
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: boardgame
            port:
              number: 80  # The port defined in the service
