apiVersion: v1
kind: Service
metadata:
  name: boardgame
  labels:
    app: boardgame
spec:
  ports:
  - name: http
    port: 80        # Change the exposed port to 80 for HTTP traffic
    protocol: TCP
    targetPort: 8080 # The container port your app is exposing
  selector:
    app: boardgame
  type: ClusterIP  # Change type to ClusterIP for Ingress routing
