apiVersion: v1
kind: Service
metadata:
  name: aqt-app
  namespace: aqt-ns
  labels:
    app: aqt-app
spec:
  ports:
  - name: http
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: aqt-app
  type: LoadBalancer
